# Generated by Django 3.2.25 on 2025-07-14 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contract_number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('serial_number', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('invoice_number', models.CharField(max_length=100)),
                ('current_location', models.CharField(choices=[('warehouse', 'Warehouse'), ('zone', 'Zone')], max_length=20)),
                ('status', models.CharField(choices=[('installed', 'Installed'), ('available', 'Available'), ('damaged', 'Damaged')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('responsible_person', models.CharField(max_length=255)),
                ('transfer_date', models.DateField(blank=True, null=True)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='contracts.contract')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse', to='contracts.contract')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('actual_delivery_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('delayed', 'Delayed')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='contracts.zone')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(blank=True, null=True)),
                ('issue_type', models.TextField()),
                ('repair_date', models.DateField(blank=True, null=True)),
                ('technician', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_cards', to='contracts.device')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='device_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='contracts.devicecategory'),
        ),
        migrations.AddField(
            model_name='device',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='contracts.warehouse'),
        ),
        migrations.AddField(
            model_name='device',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='contracts.zone'),
        ),
        migrations.CreateModel(
            name='CoordinationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField(blank=True, null=True)),
                ('target_department', models.CharField(max_length=255)),
                ('work_type', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('work_details', models.TextField()),
                ('expected_execution_date', models.DateField(blank=True, null=True)),
                ('responsible_person', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('email_sent_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordination_requests', to='contracts.zone')),
            ],
        ),
        migrations.CreateModel(
            name='ContractItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_items', to='contracts.devicecategory')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='contracts.contract')),
            ],
        ),
    ]
